//AUTH

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const RESET_APP = 'RESET_APP';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST';
export const CREATE_JOB_REQUEST_SUCCESS = 'CREATE_JOB_REQUEST_SUCCESS';
export const GET_JOB_REQUEST = 'GET_JOB_REQUEST';
export const GET_JOB_REQUEST_SUCCESS = 'GET_JOB_REQUEST_SUCCESS';
export const GET_ALL_JOB_REQUEST = 'GET_ALL_JOB_REQUEST';
export const GET_ALL_JOB_REQUEST_SUCCESS = 'GET_ALL_JOB_REQUEST_SUCCESS';
export const UPDATE_JOB_REQUEST = 'UPDATE_JOB_REQUEST';
export const UPDATE_JOB_REQUEST_SUCCESS = 'UPDATE_JOB_REQUEST_SUCCESS';
export const UPDATE_JOB_STATUS_REQUEST = 'UPDATE_JOB_STATUS_REQUEST';
export const UPDATE_JOB_STATUS_REQUEST_SUCCESS = 'UPDATE_JOB_STATUS_REQUEST_SUCCESS';
export const DELETE_JOB_REQUEST = 'DELETE_JOB_REQUEST';
export const DELETE_JOB_REQUEST_SUCCESS = 'DELETE_JOB_REQUEST_SUCCESS';
