//AUTH

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const RESET_APP = 'RESET_APP';

export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST';
export const CREATE_JOB_REQUEST_SUCCESS = 'CREATE_JOB_REQUEST_SUCCESS';
export const GET_JOB_REQUEST = 'GET_JOB_REQUEST';
export const GET_JOB_REQUEST_SUCCESS = 'GET_JOB_REQUEST_SUCCESS';
export const GET_ALL_JOB_REQUEST = 'GET_ALL_JOB_REQUEST';
export const GET_ALL_JOB_REQUEST_SUCCESS = 'GET_ALL_JOB_REQUEST_SUCCESS';
export const DELETE_JOB_REQUEST = 'DELETE_JOB_REQUEST';
export const DELETE_JOB_REQUEST_SUCCESS = 'DELETE_JOB_REQUEST_SUCCESS';
